CREATE TABLE IF NOT EXISTS vehicle (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(50) NOT NULL,
    nickname VARCHAR(50),
    license_plate VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    driver_id INTEGER NOT NULL UNIQUE,
    CONSTRAINT fk_driver_vehicle FOREIGN KEY (driver_id) REFERENCES driver(id) ON DELETE CASCADE
);